---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "nebula-exporter.name" . }}-role
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "nebula-exporter.name" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "nebula-exporter.name" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ template "nebula-exporter.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
