apiVersion: v1
kind: Service
metadata:
  name: {{ template "nebula-exporter.name" . }}
  {{- with .Values.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "nebula-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.startUp.listenPort }}
      protocol: TCP
      name: exporter-port
  selector:
    {{- include "nebula-exporter.selectorLabels" . | nindent 4 }}