apiVersion: v1
entries:
  nebula-exporter:
  - apiVersion: v1
    appVersion: v2.5.0
    created: "2021-08-16T11:54:34.149524302+08:00"
    description: Nebula Graph stats exporter for prometheus
    digest: 8b02d03f03d5d0ee7fbb2dc6fdb92ad5878409f07d928a2d778413dfd7a0b8de
    home: https://nebula-graph.io
    icon: https://github.com/vesoft-inc/nebula/raw/master/docs/logo.png
    keywords:
    - kubernetes
    - exporter
    - prometheus
    - nebula
    - graph
    maintainers:
    - email: kevin.qiao@vesoft.com
      name: kevin
      url: https://github.com/MegaByte875
    - email: kenshin.liu@vesoft.com
      name: kenshin
      url: https://github.com/kqzh
    - email: vee.zhang@vesoft.com
      name: Vee Zhang
      url: https://github.com/veezhang
    name: nebula-exporter
    sources:
    - https://github.com/vesoft-inc/nebula
    urls:
    - https://vesoft-inc.github.io/nebula-stats-exporter/charts/nebula-exporter-v0.0.5.tgz
    version: v0.0.5
generated: "2021-08-16T11:54:34.14868979+08:00"
